In [12]:
import numpy as np
import pandas as pd

In [13]:
from sklearn.datasets import load_iris
iris = load_iris()

In [14]:
x = iris.data
y = iris.target

features_names = iris.feature_names
target_name = iris.target_names


In [15]:
print(features_names)
print(target_name)

print(x[:10],y)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Spilitting the dataset

In [24]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

print(x_train.shape)
print(x_test.shape)

print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [25]:
y_train

array([2, 2, 0, 0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 0, 2, 2, 0,
       2, 1, 0, 1, 0, 1, 1, 2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 1, 1, 1, 2, 0,
       1, 0, 1, 2, 0, 2, 0, 1, 2, 0, 2, 2, 0, 2, 0, 1, 2, 2, 2, 1, 2, 0,
       1, 1, 2, 2, 0, 2, 0, 0, 1, 2, 0, 1, 1, 0, 1, 2, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 1, 2, 0, 2, 2, 0, 2])

Training the model

In [30]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

classifier_knn = KNeighborsClassifier(n_neighbors = 3)
classifier_knn.fit(x_train, y_train)
y_pred = classifier_knn.predict(x_test)

In [31]:
print("Accuracy", metrics.accuracy_score(y_test,y_pred))

Accuracy 0.9777777777777777


In [41]:
#Predicing values of random sample data
import random

sample = []

sample_size = 10

for i in range(sample_size):
  sample.append(random.sample(range(1,7),4))


predictions = classifier_knn.predict(sample)

pred_iris = [iris.target_names[i] for i in predictions]


In [42]:
# Predicted values
for i in range(sample_size):
  print(sample[i],pred_iris[i])

[3, 2, 4, 5] virginica
[4, 1, 6, 3] virginica
[5, 2, 1, 6] versicolor
[3, 6, 1, 2] setosa
[4, 2, 3, 5] virginica
[1, 6, 5, 2] versicolor
[3, 5, 2, 4] setosa
[2, 6, 4, 1] setosa
[2, 1, 5, 4] virginica
[2, 3, 1, 4] setosa
